### ISSUE TITLE
Photos not in line

### ISSUE THREAD

**Issue by geetanjaligg** [j0k3r/jekyll-flickr-photoset#7]
Photos don't appear in a block. It appears like a list. 
![screenshot from 2014-12-03 15 58 36](https://cloud.githubusercontent.com/assets/1011202/5279018/13b7e344-7b06-11e4-93ea-4cdf6bc61922.png)

**Comment by j0k3r** [comment]
Foundation seems to be included. You should include it: http://foundation.zurb.com/docs/components/clearing.html

BTW, it seems that you are using the ad-gallery version with the html render of the foundation version ...
