### ISSUE TITLE
Load API key from ENV variable

### ISSUE THREAD

**Issue by iBobik** [j0k3r/jekyll-flickr-photoset#9]
I don't want to give access to Flicker accound anybody who have access to sources for site (_config.yml), but I can save API key to environment variable on build server.

Could you add override API key config by env variable?

**Comment by gep13** [comment]
@iBobik this is already possible, as per a Pull Request that I did here:

https://github.com/j0k3r/jekyll-flickr-photoset/pull/6/files

Looks like the Readme file needs to be updated to indicate that this is possible though.  Perhaps @j0k3r can add that in.

**Comment by j0k3r** [comment]
Done :+1:

**Comment by gep13** [comment]
Nice one! :smile:

**Comment by iBobik** [comment]
Nice :-)

Jan Pobořil
http://honza.poboril.cz/
1. 11. 2015 v 2:03, Gary Ewan Park notifications@github.com:
